---
version: "2"
services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Los_Angeles"
    volumes:
      - /docker/medusa:/config
      - /media:/downloads
      - /media/TV:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
